name: drishya_picker
description: Assets picker which is inspired by messanger camera and gallery. 
version: 2.0.0-dev
homepage: https://github.com/koiralapankaj7/drishya_picker

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  camera: ^0.9.4+5
  collection: ^1.15.0
  flutter:
    sdk: flutter
  meta: ^1.7.0
  path: ^1.8.0
  photo_manager: ^1.3.10
  uuid: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/camera.png

  fonts:
    - family: CustomIcons
      fonts:
        - asset: lib/assets/fonts/CustomIcons.ttf